### ISSUE TITLE
How to use NBT crafting?

### ISSUE THREAD

**Issue by ReZLone** [Micalobia/BetterDatapacks#1]
So a feature I really hoped would have helped me is NBT crafting recipes. The idea of finally being able to create proper custom crafting recipes that show the result with the correct NBT data was incredible. Only problem I don't know how to put the nbt data into the recipe json.

**Comment by Micalobia** [comment]
I need to work on better documentation, so I'll pin this issue until I get that sorted out.

So in the result, there's an additional `tag` element, so it'd end up looking something like this
```json
{
    "type": "crafting_shapeless",
    "ingredients": [
        {
            "item": "minecraft:diamond_sword"
        }
    ],
    "result": {
        "item": "minecraft:diamond_sword",
        "count": 1,
        "tag": {
            "display": {
                "Name":"\"Shiny Diamond Sword\"",
                "Lore": ["{\"text\":\"It's Shiny!\",\"color\":\"gold\"}"]
            },
            "Enchantments": [{}]
        }
    }
}
```

The same thing can be used on the result of a shaped recipe, as well as smithing recipes although I haven't tested that one thoroughly.
